language: node_js
sudo: false
node_js:
 - "4.1"
addons:
 apt:
   sources:
   - ubuntu-toolchain-r-test
   packages:
   - gcc-4.8
   - g++-4.8
services:
 - postgresql
env:
 - TRAVIS=travis CXX=g++-4.8
before_script:
 - psql -c 'create database mwl_db;' -U postgres
 - psql -c 'use mwl_db;' -U postgres
 - psql -c 'create table users;' -U postgres
 - psql -c 'create table orders;' -U postgres
